name = "DataWidening"
uuid = "da17be00-2ff7-429b-bc2f-6c4c401c07b2"
authors = ["Dilum Aluthge <dilum@aluthge.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
